### ISSUE TITLE
Where signal come from?

### ISSUE THREAD

**Issue by stormaref** [pacoferre/netcore-signalr-angular-webrtc#1]
There is an attribute in rtc-signalr.service.ts
In sendSignal function named message that it is an ISignal 
Where this message come from?
I want to write a controller to access the hub without js and I need to know how should I pass the Signal to SendSignal method

**Comment by pacoferre** [comment]
sendSignal is a private method, used by the service to send WebRTC messages to the SignalR hub.

Those WebRTC messages are created when the WebRTC API (finally managed by Chrome, Firefox...) launches events on negotiation, conection...

If you want to create a Windows WebRTC client app, perhaps this project can help
https://github.com/microsoft/WebRTC-universal-samples/tree/master/Samples/AppRTC-UWP/appRTC_win_JS.Win10
